# pre-commit resources
# https://pre-commit.com/
# https://github.com/pre-commit/pre-commit-hooks
# https://towardsdatascience.com/pre-commit-hooks-you-must-know-ff247f5feb7e
# https://github.com/zirpu/decimal_time/blob/master/.pre-commit-config.yaml
# https://github.com/pre-commit/pre-commit/issues/1130


# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      # - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: sort-simple-yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.25.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]
  - repo: local # https://github.com/pytest-dev/pytest
    # rev: 6.2.4
    hooks:
      - id: tests
        name: run tests via pytest
        entry: pytest
        language: python
        pass_filenames: false
        'types': [python]
  - repo: https://github.com/dfm/black_nbconvert
    rev: v0.3.0
    hooks:
    - id: black_nbconvert
